[package]
name = "weather"
version = "0.1.0"
authors = ["Ali Chlaifa <alichlaifa@gmail.com>"]
edition = "2021"

[dependencies]
cxx = "1.0.95"
cxx-qt = "0.6"
cxx-qt-lib = "0.6"
url = "2.0.0"


[build-dependencies]
cxx-qt-build = { version = "0.6", features = [ "link_qt_object_files" ] }
